/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

/*
    Textdraw name: invdrop
    Description: Shows a press Y to get item message with a preview model to a player.
    Adapted for mobile: Yes
    Author: Bonnie20402
    Open-Source: Yes
                                                                                            */


#include <YSI_Coding\y_hooks>
new PlayerText:txdInvDrop_bg0[MAX_PLAYERS];
new PlayerText:txdInvDrop_bg1[MAX_PLAYERS];
new PlayerText:txdInvDrop_text[MAX_PLAYERS];
new PlayerText:txdInvDrop_model[MAX_PLAYERS];
new PlayerText:txdInvDrop_quantity[MAX_PLAYERS];


hook OnPlayerConnect(playerid)
{
	txdInvDrop_bg0[playerid] = CreatePlayerTextDraw(playerid, 382.000000, 268.000000, "LD_DUAL:white");
	PlayerTextDrawFont(playerid, txdInvDrop_bg0[playerid], 4);
	PlayerTextDrawLetterSize(playerid, txdInvDrop_bg0[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdInvDrop_bg0[playerid], 174.500000, 42.500000);
	PlayerTextDrawSetOutline(playerid, txdInvDrop_bg0[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdInvDrop_bg0[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdInvDrop_bg0[playerid], 1);
	PlayerTextDrawColor(playerid, txdInvDrop_bg0[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, txdInvDrop_bg0[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdInvDrop_bg0[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdInvDrop_bg0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdInvDrop_bg0[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdInvDrop_bg0[playerid], 0);

	txdInvDrop_bg1[playerid] = CreatePlayerTextDraw(playerid, 382.000000, 268.000000, "LD_DUAL:white");
	PlayerTextDrawFont(playerid, txdInvDrop_bg1[playerid], 4);
	PlayerTextDrawLetterSize(playerid, txdInvDrop_bg1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdInvDrop_bg1[playerid], 3.500000, 42.500000);
	PlayerTextDrawSetOutline(playerid, txdInvDrop_bg1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdInvDrop_bg1[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdInvDrop_bg1[playerid], 1);
	PlayerTextDrawColor(playerid, txdInvDrop_bg1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdInvDrop_bg1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdInvDrop_bg1[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdInvDrop_bg1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdInvDrop_bg1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdInvDrop_bg1[playerid], 0);

	txdInvDrop_text[playerid] = CreatePlayerTextDraw(playerid, 452.000000, 272.000000, "Aperte Y para pegar~n~Nome");
	PlayerTextDrawFont(playerid, txdInvDrop_text[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdInvDrop_text[playerid], 0.212500, 1.900000);
	PlayerTextDrawTextSize(playerid, txdInvDrop_text[playerid], 400.000000, 122.500000);
	PlayerTextDrawSetOutline(playerid, txdInvDrop_text[playerid], 0);
	PlayerTextDrawSetShadow(playerid, txdInvDrop_text[playerid], 1);
	PlayerTextDrawAlignment(playerid, txdInvDrop_text[playerid], 2);
	PlayerTextDrawColor(playerid, txdInvDrop_text[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdInvDrop_text[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdInvDrop_text[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdInvDrop_text[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdInvDrop_text[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdInvDrop_text[playerid], 0);

	txdInvDrop_model[playerid] = CreatePlayerTextDraw(playerid, 510.000000, 269.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, txdInvDrop_model[playerid], 5);
	PlayerTextDrawLetterSize(playerid, txdInvDrop_model[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdInvDrop_model[playerid], 47.500000, 41.000000);
	PlayerTextDrawSetOutline(playerid, txdInvDrop_model[playerid], 0);
	PlayerTextDrawSetShadow(playerid, txdInvDrop_model[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdInvDrop_model[playerid], 1);
	PlayerTextDrawColor(playerid, txdInvDrop_model[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdInvDrop_model[playerid], 0);
	PlayerTextDrawBoxColor(playerid, txdInvDrop_model[playerid], 255);
	PlayerTextDrawUseBox(playerid, txdInvDrop_model[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdInvDrop_model[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdInvDrop_model[playerid], 0);
	PlayerTextDrawSetPreviewModel(playerid, txdInvDrop_model[playerid], 0);
	PlayerTextDrawSetPreviewRot(playerid, txdInvDrop_model[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, txdInvDrop_model[playerid], 1, 1);

	txdInvDrop_quantity[playerid] = CreatePlayerTextDraw(playerid, 549.000000, 292.000000, "00");
	PlayerTextDrawFont(playerid, txdInvDrop_quantity[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdInvDrop_quantity[playerid], 0.212500, 1.900000);
	PlayerTextDrawTextSize(playerid, txdInvDrop_quantity[playerid], 390.000000, 15.500000);
	PlayerTextDrawSetOutline(playerid, txdInvDrop_quantity[playerid], 0);
	PlayerTextDrawSetShadow(playerid, txdInvDrop_quantity[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdInvDrop_quantity[playerid], 2);
	PlayerTextDrawColor(playerid, txdInvDrop_quantity[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdInvDrop_quantity[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdInvDrop_quantity[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdInvDrop_quantity[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdInvDrop_quantity[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdInvDrop_quantity[playerid], 0);
	return 1;
}

hook OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, txdInvDrop_bg0[playerid]);
	PlayerTextDrawDestroy(playerid, txdInvDrop_bg1[playerid]);
	PlayerTextDrawDestroy(playerid, txdInvDrop_text[playerid]);
	PlayerTextDrawDestroy(playerid, txdInvDrop_model[playerid]);
	PlayerTextDrawDestroy(playerid, txdInvDrop_quantity[playerid]);
	return 1;
}

//Updates the text and quantity. If the text draw is hidden, shows it. Text format: "Aperte Y para pegar ~n~ItemName". 
stock ShowPlayerTxdInvDrop(const playerid, String:text[],const modelid,const quantity)
{
    new quantityString[10];
    format(quantityString,10,"%d",quantity);
    PlayerTextDrawSetString(playerid,txdInvDrop_text[playerid],text);
    PlayerTextDrawSetString(playerid,txdInvDrop_quantity[playerid],quantityString);
    PlayerTextDrawSetPreviewModel(playerid,txdInvDrop_model[playerid],modelid);
    if(!IsPlayerTextDrawVisible(playerid,txdInvDrop_bg0[playerid])) {
        PlayerTextDrawShow(playerid, txdInvDrop_bg0[playerid]);
        PlayerTextDrawShow(playerid, txdInvDrop_bg1[playerid]);
        PlayerTextDrawShow(playerid, txdInvDrop_text[playerid]);
        PlayerTextDrawShow(playerid, txdInvDrop_model[playerid]);
        PlayerTextDrawShow(playerid, txdInvDrop_quantity[playerid]);
    }
	return 1;
}

// If the text draw is shown, hides it and returns 1. Otherwhise returns 0 and does nothing.
stock HidePlayerTxdInvDrop(const playerid) {
    if(IsPlayerTextDrawVisible(playerid,txdInvDrop_bg0[playerid])) {
        PlayerTextDrawHide(playerid, txdInvDrop_bg0[playerid]);
        PlayerTextDrawHide(playerid, txdInvDrop_bg1[playerid]);
        PlayerTextDrawHide(playerid, txdInvDrop_text[playerid]);
        PlayerTextDrawHide(playerid, txdInvDrop_model[playerid]);
        PlayerTextDrawHide(playerid, txdInvDrop_quantity[playerid]);
        return 1;
    }
    return 0;
}
