/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <YSI_Coding\y_hooks>

new PlayerText:txdLoading_bg0[MAX_PLAYERS];
new PlayerText:txdLoading_bg1[MAX_PLAYERS];
new PlayerText:txdLoading_title[MAX_PLAYERS];
new PlayerText:txdLoading_Tip[MAX_PLAYERS];
new PlayerText:txdLoading_bg2[MAX_PLAYERS];
new PlayerText:txdLoading_btn1[MAX_PLAYERS];
new PlayerText:txdLoading_btn2[MAX_PLAYERS];
new PlayerText:txdLoading_text1[MAX_PLAYERS];
new PlayerText:txdLoading_text2[MAX_PLAYERS];
new PlayerText:txdLoading_btn0[MAX_PLAYERS];
new PlayerText:txdLoading_text0[MAX_PLAYERS];
new PlayerText:txdLoading_bar2[MAX_PLAYERS];
new PlayerText:txdLoading_bar1[MAX_PLAYERS];
new PlayerText:txdLoading_bar0[MAX_PLAYERS];
new PlayerBar:txdLoading_progressbar[MAX_PLAYERS];

hook OnPlayerConnect(playerid)
{
	txdLoading_bg0[playerid] = CreatePlayerTextDraw(playerid, 39.000000, 1.000000, "_");
	PlayerTextDrawFont(playerid, txdLoading_bg0[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdLoading_bg0[playerid], 0.600000, 49.800003);
	PlayerTextDrawTextSize(playerid, txdLoading_bg0[playerid], 298.500000, 1210.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_bg0[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdLoading_bg0[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdLoading_bg0[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_bg0[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_bg0[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_bg0[playerid], 135);
	PlayerTextDrawUseBox(playerid, txdLoading_bg0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_bg0[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_bg0[playerid], 0);

	txdLoading_bg1[playerid] = CreatePlayerTextDraw(playerid, 39.000000, 1.000000, "_");
	PlayerTextDrawFont(playerid, txdLoading_bg1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdLoading_bg1[playerid], 0.600000, 2.999998);
	PlayerTextDrawTextSize(playerid, txdLoading_bg1[playerid], 298.500000, 1205.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_bg1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdLoading_bg1[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdLoading_bg1[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_bg1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_bg1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_bg1[playerid], 135);
	PlayerTextDrawUseBox(playerid, txdLoading_bg1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_bg1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_bg1[playerid], 0);

	txdLoading_title[playerid] = CreatePlayerTextDraw(playerid, 263.000000, 3.000000, "OPEN RP");
	PlayerTextDrawFont(playerid, txdLoading_title[playerid], 3);
	PlayerTextDrawLetterSize(playerid, txdLoading_title[playerid], 0.687497, 2.549998);
	PlayerTextDrawTextSize(playerid, txdLoading_title[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_title[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdLoading_title[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdLoading_title[playerid], 1);
	PlayerTextDrawColor(playerid, txdLoading_title[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_title[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_title[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_title[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdLoading_title[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_title[playerid], 0);

	txdLoading_Tip[playerid] = CreatePlayerTextDraw(playerid, 158.000000, 415.000000, "Atualmente estao 5 jogadores online.");
	PlayerTextDrawFont(playerid, txdLoading_Tip[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdLoading_Tip[playerid], 0.470833, 1.799998);
	PlayerTextDrawTextSize(playerid, txdLoading_Tip[playerid], 612.500000, -503.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_Tip[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdLoading_Tip[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdLoading_Tip[playerid], 1);
	PlayerTextDrawColor(playerid, txdLoading_Tip[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_Tip[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_Tip[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_Tip[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdLoading_Tip[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_Tip[playerid], 0);

	txdLoading_bg2[playerid] = CreatePlayerTextDraw(playerid, 39.000000, 418.000000, "_");
	PlayerTextDrawFont(playerid, txdLoading_bg2[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdLoading_bg2[playerid], 0.600000, 2.999998);
	PlayerTextDrawTextSize(playerid, txdLoading_bg2[playerid], 298.500000, 1205.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_bg2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdLoading_bg2[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdLoading_bg2[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_bg2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_bg2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_bg2[playerid], 135);
	PlayerTextDrawUseBox(playerid, txdLoading_bg2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_bg2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_bg2[playerid], 0);

	txdLoading_btn1[playerid] = CreatePlayerTextDraw(playerid, 121.000000, 213.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, txdLoading_btn1[playerid], 4);
	PlayerTextDrawLetterSize(playerid, txdLoading_btn1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdLoading_btn1[playerid], 390.000000, 61.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_btn1[playerid], 2);
	PlayerTextDrawSetShadow(playerid, txdLoading_btn1[playerid], 1);
	PlayerTextDrawAlignment(playerid, txdLoading_btn1[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_btn1[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_btn1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_btn1[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_btn1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_btn1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_btn1[playerid], 1);

	txdLoading_btn2[playerid] = CreatePlayerTextDraw(playerid, 121.000000, 283.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, txdLoading_btn2[playerid], 4);
	PlayerTextDrawLetterSize(playerid, txdLoading_btn2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdLoading_btn2[playerid], 390.000000, 61.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_btn2[playerid], 2);
	PlayerTextDrawSetShadow(playerid, txdLoading_btn2[playerid], 1);
	PlayerTextDrawAlignment(playerid, txdLoading_btn2[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_btn2[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_btn2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_btn2[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_btn2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_btn2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_btn2[playerid], 1);

	txdLoading_text1[playerid] = CreatePlayerTextDraw(playerid, 219.000000, 216.000000, "CHANGELOG");
	PlayerTextDrawFont(playerid, txdLoading_text1[playerid], 2);
	PlayerTextDrawLetterSize(playerid, txdLoading_text1[playerid], 0.883333, 4.900002);
	PlayerTextDrawTextSize(playerid, txdLoading_text1[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_text1[playerid], 0);
	PlayerTextDrawSetShadow(playerid, txdLoading_text1[playerid], 2);
	PlayerTextDrawAlignment(playerid, txdLoading_text1[playerid], 1);
	PlayerTextDrawColor(playerid, txdLoading_text1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_text1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_text1[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_text1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdLoading_text1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_text1[playerid], 0);

	txdLoading_text2[playerid] = CreatePlayerTextDraw(playerid, 271.000000, 284.000000, "SAIR");
	PlayerTextDrawFont(playerid, txdLoading_text2[playerid], 2);
	PlayerTextDrawLetterSize(playerid, txdLoading_text2[playerid], 0.883333, 4.900002);
	PlayerTextDrawTextSize(playerid, txdLoading_text2[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_text2[playerid], 0);
	PlayerTextDrawSetShadow(playerid, txdLoading_text2[playerid], 2);
	PlayerTextDrawAlignment(playerid, txdLoading_text2[playerid], 1);
	PlayerTextDrawColor(playerid, txdLoading_text2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_text2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_text2[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_text2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdLoading_text2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_text2[playerid], 0);

	txdLoading_btn0[playerid] = CreatePlayerTextDraw(playerid, 121.000000, 141.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, txdLoading_btn0[playerid], 4);
	PlayerTextDrawLetterSize(playerid, txdLoading_btn0[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdLoading_btn0[playerid], 390.000000, 61.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_btn0[playerid], 2);
	PlayerTextDrawSetShadow(playerid, txdLoading_btn0[playerid], 1);
	PlayerTextDrawAlignment(playerid, txdLoading_btn0[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_btn0[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_btn0[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_btn0[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_btn0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_btn0[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_btn0[playerid], 1);

	txdLoading_text0[playerid] = CreatePlayerTextDraw(playerid, 260.000000, 144.000000, "JOGAR");
	PlayerTextDrawFont(playerid, txdLoading_text0[playerid], 2);
	PlayerTextDrawLetterSize(playerid, txdLoading_text0[playerid], 0.883333, 4.900002);
	PlayerTextDrawTextSize(playerid, txdLoading_text0[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_text0[playerid], 0);
	PlayerTextDrawSetShadow(playerid, txdLoading_text0[playerid], 2);
	PlayerTextDrawAlignment(playerid, txdLoading_text0[playerid], 1);
	PlayerTextDrawColor(playerid, txdLoading_text0[playerid], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_text0[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_text0[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_text0[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdLoading_text0[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_text0[playerid], 0);

	txdLoading_bar2[playerid] = CreatePlayerTextDraw(playerid, 121.000000, 283.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, txdLoading_bar2[playerid], 4);
	PlayerTextDrawLetterSize(playerid, txdLoading_bar2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdLoading_bar2[playerid], 4.000000, 61.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_bar2[playerid], 2);
	PlayerTextDrawSetShadow(playerid, txdLoading_bar2[playerid], 1);
	PlayerTextDrawAlignment(playerid, txdLoading_bar2[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_bar2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_bar2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_bar2[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_bar2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_bar2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_bar2[playerid], 1);

	txdLoading_bar1[playerid] = CreatePlayerTextDraw(playerid, 121.000000, 213.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, txdLoading_bar1[playerid], 4);
	PlayerTextDrawLetterSize(playerid, txdLoading_bar1[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdLoading_bar1[playerid], 4.000000, 61.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_bar1[playerid], 2);
	PlayerTextDrawSetShadow(playerid, txdLoading_bar1[playerid], 1);
	PlayerTextDrawAlignment(playerid, txdLoading_bar1[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_bar1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_bar1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_bar1[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_bar1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_bar1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_bar1[playerid], 0);

	txdLoading_bar0[playerid] = CreatePlayerTextDraw(playerid, 121.000000, 141.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, txdLoading_bar0[playerid], 4);
	PlayerTextDrawLetterSize(playerid, txdLoading_bar0[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdLoading_bar0[playerid], 4.000000, 61.000000);
	PlayerTextDrawSetOutline(playerid, txdLoading_bar0[playerid], 2);
	PlayerTextDrawSetShadow(playerid, txdLoading_bar0[playerid], 1);
	PlayerTextDrawAlignment(playerid, txdLoading_bar0[playerid], 2);
	PlayerTextDrawColor(playerid, txdLoading_bar0[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdLoading_bar0[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdLoading_bar0[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdLoading_bar0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdLoading_bar0[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdLoading_bar0[playerid], 0);

	txdLoading_progressbar[playerid] = CreatePlayerProgressBar(playerid, 0.000000, 30.000000, 645.000000, -2.000000, -1, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, txdLoading_progressbar[playerid],0.0);

	return 1;
}

hook OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, txdLoading_bg0[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_bg1[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_title[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_Tip[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_bg2[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_btn1[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_btn2[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_text1[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_text2[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_btn0[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_text0[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_bar2[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_bar1[playerid]);
	PlayerTextDrawDestroy(playerid, txdLoading_bar0[playerid]);
	DestroyPlayerProgressBar(playerid, txdLoading_progressbar[playerid]);
	return 1;
}

forward ShowPlayerTxdLoading(playerid,isLoaded);
public ShowPlayerTxdLoading(playerid,isLoaded)
{
	PlayerTextDrawShow(playerid, txdLoading_bg0[playerid]);
	PlayerTextDrawShow(playerid, txdLoading_bg1[playerid]);
	PlayerTextDrawShow(playerid, txdLoading_title[playerid]);
	PlayerTextDrawShow(playerid, txdLoading_Tip[playerid]);
	PlayerTextDrawShow(playerid, txdLoading_bg2[playerid]);
	ShowPlayerProgressBar(playerid, txdLoading_progressbar[playerid]);
	if(isLoaded) {
		PlayerTextDrawShow(playerid, txdLoading_btn1[playerid]);
		PlayerTextDrawShow(playerid, txdLoading_btn2[playerid]);
		PlayerTextDrawShow(playerid, txdLoading_btn0[playerid]);
		PlayerTextDrawShow(playerid, txdLoading_text0[playerid]);
		PlayerTextDrawShow(playerid, txdLoading_text1[playerid]);
		PlayerTextDrawShow(playerid, txdLoading_text2[playerid]);
		PlayerTextDrawShow(playerid, txdLoading_bar2[playerid]);
		PlayerTextDrawShow(playerid, txdLoading_bar1[playerid]);
		PlayerTextDrawShow(playerid, txdLoading_bar0[playerid]);
		SelectTextDraw(playerid,0x00FF00FF);
	}
	return 0;
}
forward HidePlayerTxdLoading(playerid);
public HidePlayerTxdLoading(playerid) {
	PlayerTextDrawHide(playerid, txdLoading_bg0[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_bg1[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_title[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_Tip[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_bg2[playerid]);
	HidePlayerProgressBar(playerid, txdLoading_progressbar[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_btn1[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_btn2[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_btn0[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_text0[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_text1[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_text2[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_bar2[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_bar1[playerid]);
	PlayerTextDrawHide(playerid, txdLoading_bar0[playerid]);
}
stock SetPlayerTxdLoadingText(playerid,String:text[]) {
	PlayerTextDrawSetString(playerid,txdLoading_Tip[playerid],text);
	return 1;
}
stock SetPlayerTxdLoadingProgress(playerid,Float:newProgress) {
	SetPlayerProgressBarValue(playerid,txdLoading_progressbar[playerid],newProgress);
	return 1;
}
stock Float:GetPlayerTxdLoadingProgress(playerid) {
	return GetPlayerProgressBarValue(playerid,txdLoading_progressbar[playerid]);
}
