/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <YSI_Coding\y_hooks>

new PlayerText:txdPayday_text[MAX_PLAYERS];

hook OnPlayerConnect(playerid)
{
	txdPayday_text[playerid] = CreatePlayerTextDraw(playerid, 540.000000, 98.000000, "payday 00:00:00");
	PlayerTextDrawFont(playerid, txdPayday_text[playerid], 3);
	PlayerTextDrawLetterSize(playerid, txdPayday_text[playerid], 0.233333, 2.000000);
	PlayerTextDrawTextSize(playerid, txdPayday_text[playerid], 623.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, txdPayday_text[playerid], 0);
	PlayerTextDrawSetShadow(playerid, txdPayday_text[playerid], 1);
	PlayerTextDrawAlignment(playerid, txdPayday_text[playerid], 1);
	PlayerTextDrawColor(playerid, txdPayday_text[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdPayday_text[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdPayday_text[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdPayday_text[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdPayday_text[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdPayday_text[playerid], 0);

	return 1;
}

hook OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, txdPayday_text[playerid]);
	return 1;
}

stock ShowPlayerTxdPaydayCounter(playerid, String:text[]) {
    if(!IsPlayerTextDrawVisible(playerid,txdPayday_text[playerid]))PlayerTextDrawShow(playerid, txdPayday_text[playerid]);
    PlayerTextDrawSetString(playerid,txdPayday_text[playerid],text);
	return 1;
}
