/*
This file was generated by Nickk's PlayerTextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>
#include <YSI_Coding\y_hooks>

new PlayerText:txdscreenMsg[MAX_PLAYERS];

hook OnPlayerConnect(playerid)
{
	txdscreenMsg[playerid] = CreatePlayerTextDraw(playerid, 183.000000, 365.000000, "mensagem");
	PlayerTextDrawFont(playerid, txdscreenMsg[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdscreenMsg[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdscreenMsg[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, txdscreenMsg[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdscreenMsg[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdscreenMsg[playerid], 1);
	PlayerTextDrawColor(playerid, txdscreenMsg[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdscreenMsg[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdscreenMsg[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdscreenMsg[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdscreenMsg[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdscreenMsg[playerid], 0);
	return 1;
}
hook OnPlayerDisconnect(playerid,reason)
{
	PlayerTextDrawDestroy(playerid, txdscreenMsg[playerid]);
	return 1;
}
