/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/


//Requires "progress2" include by Southclaws
//Download: https://github.com/Southclaws/progress2/releases

new PlayerText:txdloadingBackground1[MAX_PLAYERS];
new PlayerText:txdloadingTitle[MAX_PLAYERS];
new PlayerText:txdloadingBackground2[MAX_PLAYERS];
new PlayerText:txdloadingMessage[MAX_PLAYERS];
new PlayerText:txdloadingVersion[MAX_PLAYERS];
new PlayerBar:txdloadingProgress[MAX_PLAYERS];
#include <YSI_Coding\y_hooks>
hook OnPlayerConnect(playerid)
{
	txdloadingBackground1[playerid] = CreatePlayerTextDraw(playerid, 40.000000, 3.000000, "_");
	PlayerTextDrawFont(playerid, txdloadingBackground1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdloadingBackground1[playerid], 0.391666, 49.150001);
	PlayerTextDrawTextSize(playerid, txdloadingBackground1[playerid], 323.500000, 1195.000000);
	PlayerTextDrawSetOutline(playerid, txdloadingBackground1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdloadingBackground1[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdloadingBackground1[playerid], 2);
	PlayerTextDrawColor(playerid, txdloadingBackground1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdloadingBackground1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdloadingBackground1[playerid], 255);
	PlayerTextDrawUseBox(playerid, txdloadingBackground1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdloadingBackground1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdloadingBackground1[playerid], 0);

	txdloadingTitle[playerid] = CreatePlayerTextDraw(playerid, 283.000000, 165.000000, "OpenRP");
	PlayerTextDrawFont(playerid, txdloadingTitle[playerid], 3);
	PlayerTextDrawLetterSize(playerid, txdloadingTitle[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, txdloadingTitle[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, txdloadingTitle[playerid], 4);
	PlayerTextDrawSetShadow(playerid, txdloadingTitle[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdloadingTitle[playerid], 1);
	PlayerTextDrawColor(playerid, txdloadingTitle[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdloadingTitle[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdloadingTitle[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdloadingTitle[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdloadingTitle[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdloadingTitle[playerid], 0);

	txdloadingBackground2[playerid] = CreatePlayerTextDraw(playerid, 323.000000, 144.000000, "_");
	PlayerTextDrawFont(playerid, txdloadingBackground2[playerid], 1);
	PlayerTextDrawLetterSize(playerid, txdloadingBackground2[playerid], 0.808333, 9.900005);
	PlayerTextDrawTextSize(playerid, txdloadingBackground2[playerid], 352.000000, 225.000000);
	PlayerTextDrawSetOutline(playerid, txdloadingBackground2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdloadingBackground2[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdloadingBackground2[playerid], 2);
	PlayerTextDrawColor(playerid, txdloadingBackground2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdloadingBackground2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdloadingBackground2[playerid], -176);
	PlayerTextDrawUseBox(playerid, txdloadingBackground2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, txdloadingBackground2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdloadingBackground2[playerid], 0);

	txdloadingMessage[playerid] = CreatePlayerTextDraw(playerid, 317.000000, 195.000000, "MENSAGEM DE CARREGAMENTO");
	PlayerTextDrawFont(playerid, txdloadingMessage[playerid], 2);
	PlayerTextDrawLetterSize(playerid, txdloadingMessage[playerid], 0.308333, 2.000000);
	PlayerTextDrawTextSize(playerid, txdloadingMessage[playerid], 467.500000, 210.000000);
	PlayerTextDrawSetOutline(playerid, txdloadingMessage[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdloadingMessage[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdloadingMessage[playerid], 2);
	PlayerTextDrawColor(playerid, txdloadingMessage[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, txdloadingMessage[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdloadingMessage[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdloadingMessage[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdloadingMessage[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdloadingMessage[playerid], 0);

	txdloadingVersion[playerid] = CreatePlayerTextDraw(playerid, 396.000000, 139.000000, "v1.0.0");
	PlayerTextDrawFont(playerid, txdloadingVersion[playerid], 2);
	PlayerTextDrawLetterSize(playerid, txdloadingVersion[playerid], 0.312500, 1.950000);
	PlayerTextDrawTextSize(playerid, txdloadingVersion[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, txdloadingVersion[playerid], 1);
	PlayerTextDrawSetShadow(playerid, txdloadingVersion[playerid], 0);
	PlayerTextDrawAlignment(playerid, txdloadingVersion[playerid], 1);
	PlayerTextDrawColor(playerid, txdloadingVersion[playerid], 16711935);
	PlayerTextDrawBackgroundColor(playerid, txdloadingVersion[playerid], 255);
	PlayerTextDrawBoxColor(playerid, txdloadingVersion[playerid], 50);
	PlayerTextDrawUseBox(playerid, txdloadingVersion[playerid], 0);
	PlayerTextDrawSetProportional(playerid, txdloadingVersion[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, txdloadingVersion[playerid], 0);

	txdloadingProgress[playerid] = CreatePlayerProgressBar(playerid, 209.000000, 237.000000, 232.000000, -4.000000, -1, 100.000000, 0);
	SetPlayerProgressBarValue(playerid, txdloadingProgress[playerid], 50.000000);

	return 1;
}
#include <YSI_Coding\y_hooks>
hook OnPlayerDisconnect(playerid,reason)
{
	PlayerTextDrawDestroy(playerid, txdloadingBackground1[playerid]);
	PlayerTextDrawDestroy(playerid, txdloadingTitle[playerid]);
	PlayerTextDrawDestroy(playerid, txdloadingBackground2[playerid]);
	PlayerTextDrawDestroy(playerid, txdloadingMessage[playerid]);
	PlayerTextDrawDestroy(playerid, txdloadingVersion[playerid]);
	DestroyPlayerProgressBar(playerid, txdloadingProgress[playerid]);
	return 1;
}

